// S&P 500 constituents (snapshot July 2026, via github.com/datasets/s-and-p-500-companies).
// Regenerate by re-running the generator against a fresh constituents.csv.
const SP500 = [
  { t: "A", n: "Agilent Technologies", s: "Healthcare" },
  { t: "AAPL", n: "Apple Inc.", s: "Technology" },
  { t: "ABBV", n: "AbbVie", s: "Healthcare" },
  { t: "ABNB", n: "Airbnb", s: "Consumer Disc." },
  { t: "ABT", n: "Abbott Laboratories", s: "Healthcare" },
  { t: "ACGL", n: "Arch Capital Group", s: "Financials" },
  { t: "ACN", n: "Accenture", s: "Technology" },
  { t: "ADBE", n: "Adobe Inc.", s: "Technology" },
  { t: "ADI", n: "Analog Devices", s: "Technology" },
  { t: "ADM", n: "Archer Daniels Midland", s: "Consumer Staples" },
  { t: "ADP", n: "Automatic Data Processing", s: "Industrials" },
  { t: "ADSK", n: "Autodesk", s: "Technology" },
  { t: "AEE", n: "Ameren", s: "Utilities" },
  { t: "AEP", n: "American Electric Power", s: "Utilities" },
  { t: "AES", n: "AES Corporation", s: "Utilities" },
  { t: "AFL", n: "Aflac", s: "Financials" },
  { t: "AIG", n: "American International Group", s: "Financials" },
  { t: "AIZ", n: "Assurant", s: "Financials" },
  { t: "AJG", n: "Arthur J. Gallagher & Co.", s: "Financials" },
  { t: "AKAM", n: "Akamai Technologies", s: "Technology" },
  { t: "ALB", n: "Albemarle Corporation", s: "Materials" },
  { t: "ALGN", n: "Align Technology", s: "Healthcare" },
  { t: "ALL", n: "Allstate", s: "Financials" },
  { t: "ALLE", n: "Allegion", s: "Industrials" },
  { t: "AMAT", n: "Applied Materials", s: "Technology" },
  { t: "AMCR", n: "Amcor", s: "Materials" },
  { t: "AMD", n: "Advanced Micro Devices", s: "Technology" },
  { t: "AME", n: "Ametek", s: "Industrials" },
  { t: "AMGN", n: "Amgen", s: "Healthcare" },
  { t: "AMP", n: "Ameriprise Financial", s: "Financials" },
  { t: "AMT", n: "American Tower", s: "Real Estate" },
  { t: "AMZN", n: "Amazon", s: "Consumer Disc." },
  { t: "ANET", n: "Arista Networks", s: "Technology" },
  { t: "AON", n: "Aon plc", s: "Financials" },
  { t: "AOS", n: "A. O. Smith", s: "Industrials" },
  { t: "APA", n: "APA Corporation", s: "Energy" },
  { t: "APD", n: "Air Products", s: "Materials" },
  { t: "APH", n: "Amphenol", s: "Technology" },
  { t: "APO", n: "Apollo Global Management", s: "Financials" },
  { t: "APP", n: "AppLovin", s: "Technology" },
  { t: "APTV", n: "Aptiv", s: "Consumer Disc." },
  { t: "ARE", n: "Alexandria Real Estate Equities", s: "Real Estate" },
  { t: "ARES", n: "Ares Management", s: "Financials" },
  { t: "ATO", n: "Atmos Energy", s: "Utilities" },
  { t: "AVB", n: "AvalonBay Communities", s: "Real Estate" },
  { t: "AVGO", n: "Broadcom", s: "Technology" },
  { t: "AVY", n: "Avery Dennison", s: "Materials" },
  { t: "AWK", n: "American Water Works", s: "Utilities" },
  { t: "AXON", n: "Axon Enterprise", s: "Industrials" },
  { t: "AXP", n: "American Express", s: "Financials" },
  { t: "AZO", n: "AutoZone", s: "Consumer Disc." },
  { t: "BA", n: "Boeing", s: "Industrials" },
  { t: "BAC", n: "Bank of America", s: "Financials" },
  { t: "BALL", n: "Ball Corporation", s: "Materials" },
  { t: "BAX", n: "Baxter International", s: "Healthcare" },
  { t: "BBY", n: "Best Buy", s: "Consumer Disc." },
  { t: "BDX", n: "Becton Dickinson", s: "Healthcare" },
  { t: "BEN", n: "Franklin Resources", s: "Financials" },
  { t: "BF.B", n: "Brown–Forman", s: "Consumer Staples" },
  { t: "BG", n: "Bunge Global", s: "Consumer Staples" },
  { t: "BIIB", n: "Biogen", s: "Healthcare" },
  { t: "BKNG", n: "Booking Holdings", s: "Consumer Disc." },
  { t: "BKR", n: "Baker Hughes", s: "Energy" },
  { t: "BLDR", n: "Builders FirstSource", s: "Industrials" },
  { t: "BLK", n: "BlackRock", s: "Financials" },
  { t: "BMY", n: "Bristol Myers Squibb", s: "Healthcare" },
  { t: "BNY", n: "BNY Mellon", s: "Financials" },
  { t: "BR", n: "Broadridge Financial Solutions", s: "Industrials" },
  { t: "BRK.B", n: "Berkshire Hathaway", s: "Financials" },
  { t: "BRO", n: "Brown & Brown", s: "Financials" },
  { t: "BSX", n: "Boston Scientific", s: "Healthcare" },
  { t: "BX", n: "Blackstone Inc.", s: "Financials" },
  { t: "BXP", n: "BXP, Inc.", s: "Real Estate" },
  { t: "C", n: "Citigroup", s: "Financials" },
  { t: "CAH", n: "Cardinal Health", s: "Healthcare" },
  { t: "CARR", n: "Carrier Global", s: "Industrials" },
  { t: "CASY", n: "Casey's", s: "Consumer Staples" },
  { t: "CAT", n: "Caterpillar Inc.", s: "Industrials" },
  { t: "CB", n: "Chubb Limited", s: "Financials" },
  { t: "CBOE", n: "Cboe Global Markets", s: "Financials" },
  { t: "CBRE", n: "CBRE Group", s: "Real Estate" },
  { t: "CCI", n: "Crown Castle", s: "Real Estate" },
  { t: "CCL", n: "Carnival Corporation", s: "Consumer Disc." },
  { t: "CDNS", n: "Cadence Design Systems", s: "Technology" },
  { t: "CDW", n: "CDW Corporation", s: "Technology" },
  { t: "CEG", n: "Constellation Energy", s: "Utilities" },
  { t: "CF", n: "CF Industries", s: "Materials" },
  { t: "CFG", n: "Citizens Financial Group", s: "Financials" },
  { t: "CHD", n: "Church & Dwight", s: "Consumer Staples" },
  { t: "CHRW", n: "C.H. Robinson", s: "Industrials" },
  { t: "CHTR", n: "Charter Communications", s: "Communication" },
  { t: "CI", n: "Cigna", s: "Healthcare" },
  { t: "CIEN", n: "Ciena", s: "Technology" },
  { t: "CINF", n: "Cincinnati Financial", s: "Financials" },
  { t: "CL", n: "Colgate-Palmolive", s: "Consumer Staples" },
  { t: "CLX", n: "Clorox", s: "Consumer Staples" },
  { t: "CMCSA", n: "Comcast", s: "Communication" },
  { t: "CME", n: "CME Group", s: "Financials" },
  { t: "CMG", n: "Chipotle Mexican Grill", s: "Consumer Disc." },
  { t: "CMI", n: "Cummins", s: "Industrials" },
  { t: "CMS", n: "CMS Energy", s: "Utilities" },
  { t: "CNC", n: "Centene Corporation", s: "Healthcare" },
  { t: "CNP", n: "CenterPoint Energy", s: "Utilities" },
  { t: "COF", n: "Capital One", s: "Financials" },
  { t: "COHR", n: "Coherent Corp.", s: "Technology" },
  { t: "COIN", n: "Coinbase", s: "Financials" },
  { t: "COO", n: "Cooper Companies (The)", s: "Healthcare" },
  { t: "COP", n: "ConocoPhillips", s: "Energy" },
  { t: "COR", n: "Cencora", s: "Healthcare" },
  { t: "COST", n: "Costco", s: "Consumer Staples" },
  { t: "CPAY", n: "Corpay", s: "Financials" },
  { t: "CPRT", n: "Copart", s: "Industrials" },
  { t: "CPT", n: "Camden Property Trust", s: "Real Estate" },
  { t: "CRH", n: "CRH plc", s: "Materials" },
  { t: "CRL", n: "Charles River Laboratories", s: "Healthcare" },
  { t: "CRM", n: "Salesforce", s: "Technology" },
  { t: "CRWD", n: "CrowdStrike", s: "Technology" },
  { t: "CSCO", n: "Cisco", s: "Technology" },
  { t: "CSGP", n: "CoStar Group", s: "Real Estate" },
  { t: "CSX", n: "CSX Corporation", s: "Industrials" },
  { t: "CTAS", n: "Cintas", s: "Industrials" },
  { t: "CTSH", n: "Cognizant", s: "Technology" },
  { t: "CTVA", n: "Corteva", s: "Materials" },
  { t: "CVNA", n: "Carvana", s: "Consumer Disc." },
  { t: "CVS", n: "CVS Health", s: "Healthcare" },
  { t: "CVX", n: "Chevron Corporation", s: "Energy" },
  { t: "D", n: "Dominion Energy", s: "Utilities" },
  { t: "DAL", n: "Delta Air Lines", s: "Industrials" },
  { t: "DASH", n: "DoorDash", s: "Consumer Disc." },
  { t: "DD", n: "DuPont", s: "Materials" },
  { t: "DDOG", n: "Datadog", s: "Technology" },
  { t: "DE", n: "Deere & Company", s: "Industrials" },
  { t: "DECK", n: "Deckers Brands", s: "Consumer Disc." },
  { t: "DELL", n: "Dell Technologies", s: "Technology" },
  { t: "DG", n: "Dollar General", s: "Consumer Staples" },
  { t: "DGX", n: "Quest Diagnostics", s: "Healthcare" },
  { t: "DHI", n: "D. R. Horton", s: "Consumer Disc." },
  { t: "DHR", n: "Danaher Corporation", s: "Healthcare" },
  { t: "DIS", n: "Walt Disney Company (The)", s: "Communication" },
  { t: "DLR", n: "Digital Realty", s: "Real Estate" },
  { t: "DLTR", n: "Dollar Tree", s: "Consumer Staples" },
  { t: "DOC", n: "Healthpeak Properties", s: "Real Estate" },
  { t: "DOV", n: "Dover Corporation", s: "Industrials" },
  { t: "DOW", n: "Dow Inc.", s: "Materials" },
  { t: "DPZ", n: "Domino's", s: "Consumer Disc." },
  { t: "DRI", n: "Darden Restaurants", s: "Consumer Disc." },
  { t: "DTE", n: "DTE Energy", s: "Utilities" },
  { t: "DUK", n: "Duke Energy", s: "Utilities" },
  { t: "DVA", n: "DaVita", s: "Healthcare" },
  { t: "DVN", n: "Devon Energy", s: "Energy" },
  { t: "DXCM", n: "Dexcom", s: "Healthcare" },
  { t: "EA", n: "Electronic Arts", s: "Communication" },
  { t: "EBAY", n: "eBay Inc.", s: "Consumer Disc." },
  { t: "ECHO", n: "EchoStar", s: "Communication" },
  { t: "ECL", n: "Ecolab", s: "Materials" },
  { t: "ED", n: "Consolidated Edison", s: "Utilities" },
  { t: "EFX", n: "Equifax", s: "Industrials" },
  { t: "EG", n: "Everest Group", s: "Financials" },
  { t: "EIX", n: "Edison International", s: "Utilities" },
  { t: "EL", n: "Estée Lauder Companies (The)", s: "Consumer Staples" },
  { t: "ELV", n: "Elevance Health", s: "Healthcare" },
  { t: "EME", n: "Emcor", s: "Industrials" },
  { t: "EMR", n: "Emerson Electric", s: "Industrials" },
  { t: "EOG", n: "EOG Resources", s: "Energy" },
  { t: "EQIX", n: "Equinix", s: "Real Estate" },
  { t: "EQR", n: "Equity Residential", s: "Real Estate" },
  { t: "EQT", n: "EQT Corporation", s: "Energy" },
  { t: "ERIE", n: "Erie Indemnity", s: "Financials" },
  { t: "ES", n: "Eversource Energy", s: "Utilities" },
  { t: "ESS", n: "Essex Property Trust", s: "Real Estate" },
  { t: "ETN", n: "Eaton Corporation", s: "Industrials" },
  { t: "ETR", n: "Entergy", s: "Utilities" },
  { t: "EVRG", n: "Evergy", s: "Utilities" },
  { t: "EW", n: "Edwards Lifesciences", s: "Healthcare" },
  { t: "EXC", n: "Exelon", s: "Utilities" },
  { t: "EXE", n: "Expand Energy", s: "Energy" },
  { t: "EXPD", n: "Expeditors International", s: "Industrials" },
  { t: "EXPE", n: "Expedia Group", s: "Consumer Disc." },
  { t: "EXR", n: "Extra Space Storage", s: "Real Estate" },
  { t: "F", n: "Ford Motor Company", s: "Consumer Disc." },
  { t: "FANG", n: "Diamondback Energy", s: "Energy" },
  { t: "FAST", n: "Fastenal", s: "Industrials" },
  { t: "FCX", n: "Freeport-McMoRan", s: "Materials" },
  { t: "FDS", n: "FactSet", s: "Financials" },
  { t: "FDX", n: "FedEx", s: "Industrials" },
  { t: "FDXF", n: "FedEx Freight", s: "Industrials" },
  { t: "FE", n: "FirstEnergy", s: "Utilities" },
  { t: "FFIV", n: "F5, Inc.", s: "Technology" },
  { t: "FICO", n: "Fair Isaac", s: "Technology" },
  { t: "FIS", n: "Fidelity National Information Services", s: "Financials" },
  { t: "FISV", n: "Fiserv", s: "Financials" },
  { t: "FITB", n: "Fifth Third Bancorp", s: "Financials" },
  { t: "FIX", n: "Comfort Systems USA", s: "Industrials" },
  { t: "FLEX", n: "Flex Ltd.", s: "Technology" },
  { t: "FOX", n: "Fox Corporation (Class B)", s: "Communication" },
  { t: "FOXA", n: "Fox Corporation (Class A)", s: "Communication" },
  { t: "FRT", n: "Federal Realty Investment Trust", s: "Real Estate" },
  { t: "FSLR", n: "First Solar", s: "Technology" },
  { t: "FTNT", n: "Fortinet", s: "Technology" },
  { t: "FTV", n: "Fortive", s: "Industrials" },
  { t: "GD", n: "General Dynamics", s: "Industrials" },
  { t: "GDDY", n: "GoDaddy", s: "Technology" },
  { t: "GE", n: "GE Aerospace", s: "Industrials" },
  { t: "GEHC", n: "GE HealthCare", s: "Healthcare" },
  { t: "GEN", n: "Gen Digital", s: "Technology" },
  { t: "GEV", n: "GE Vernova", s: "Industrials" },
  { t: "GILD", n: "Gilead Sciences", s: "Healthcare" },
  { t: "GIS", n: "General Mills", s: "Consumer Staples" },
  { t: "GL", n: "Globe Life", s: "Financials" },
  { t: "GLW", n: "Corning Inc.", s: "Technology" },
  { t: "GM", n: "General Motors", s: "Consumer Disc." },
  { t: "GNRC", n: "Generac", s: "Industrials" },
  { t: "GOOG", n: "Alphabet Inc. (Class C)", s: "Communication" },
  { t: "GOOGL", n: "Alphabet Inc. (Class A)", s: "Communication" },
  { t: "GPC", n: "Genuine Parts Company", s: "Consumer Disc." },
  { t: "GPN", n: "Global Payments", s: "Financials" },
  { t: "GRMN", n: "Garmin", s: "Consumer Disc." },
  { t: "GS", n: "Goldman Sachs", s: "Financials" },
  { t: "GWW", n: "W. W. Grainger", s: "Industrials" },
  { t: "HAL", n: "Halliburton", s: "Energy" },
  { t: "HAS", n: "Hasbro", s: "Consumer Disc." },
  { t: "HBAN", n: "Huntington Bancshares", s: "Financials" },
  { t: "HCA", n: "HCA Healthcare", s: "Healthcare" },
  { t: "HD", n: "Home Depot (The)", s: "Consumer Disc." },
  { t: "HIG", n: "Hartford (The)", s: "Financials" },
  { t: "HII", n: "Huntington Ingalls Industries", s: "Industrials" },
  { t: "HLT", n: "Hilton Worldwide", s: "Consumer Disc." },
  { t: "HON", n: "Honeywell Technologies", s: "Industrials" },
  { t: "HONA", n: "Honeywell Aerospace", s: "Industrials" },
  { t: "HOOD", n: "Robinhood Markets", s: "Financials" },
  { t: "HPE", n: "Hewlett Packard Enterprise", s: "Technology" },
  { t: "HPQ", n: "HP Inc.", s: "Technology" },
  { t: "HRL", n: "Hormel Foods", s: "Consumer Staples" },
  { t: "HSIC", n: "Henry Schein", s: "Healthcare" },
  { t: "HST", n: "Host Hotels & Resorts", s: "Real Estate" },
  { t: "HSY", n: "Hershey Company (The)", s: "Consumer Staples" },
  { t: "HUBB", n: "Hubbell Incorporated", s: "Industrials" },
  { t: "HUM", n: "Humana", s: "Healthcare" },
  { t: "HWM", n: "Howmet Aerospace", s: "Industrials" },
  { t: "IBKR", n: "Interactive Brokers", s: "Financials" },
  { t: "IBM", n: "IBM", s: "Technology" },
  { t: "ICE", n: "Intercontinental Exchange", s: "Financials" },
  { t: "IDXX", n: "Idexx Laboratories", s: "Healthcare" },
  { t: "IEX", n: "IDEX Corporation", s: "Industrials" },
  { t: "IFF", n: "International Flavors & Fragrances", s: "Materials" },
  { t: "INCY", n: "Incyte", s: "Healthcare" },
  { t: "INTC", n: "Intel", s: "Technology" },
  { t: "INTU", n: "Intuit", s: "Technology" },
  { t: "INVH", n: "Invitation Homes", s: "Real Estate" },
  { t: "IP", n: "International Paper", s: "Materials" },
  { t: "IQV", n: "IQVIA", s: "Healthcare" },
  { t: "IR", n: "Ingersoll Rand", s: "Industrials" },
  { t: "IRM", n: "Iron Mountain", s: "Real Estate" },
  { t: "ISRG", n: "Intuitive Surgical", s: "Healthcare" },
  { t: "IT", n: "Gartner", s: "Technology" },
  { t: "ITW", n: "Illinois Tool Works", s: "Industrials" },
  { t: "IVZ", n: "Invesco", s: "Financials" },
  { t: "J", n: "Jacobs Solutions", s: "Industrials" },
  { t: "JBHT", n: "J.B. Hunt", s: "Industrials" },
  { t: "JBL", n: "Jabil", s: "Technology" },
  { t: "JCI", n: "Johnson Controls", s: "Industrials" },
  { t: "JKHY", n: "Jack Henry & Associates", s: "Financials" },
  { t: "JNJ", n: "Johnson & Johnson", s: "Healthcare" },
  { t: "JPM", n: "JPMorgan Chase", s: "Financials" },
  { t: "KDP", n: "Keurig Dr Pepper", s: "Consumer Staples" },
  { t: "KEY", n: "KeyCorp", s: "Financials" },
  { t: "KEYS", n: "Keysight Technologies", s: "Technology" },
  { t: "KHC", n: "Kraft Heinz", s: "Consumer Staples" },
  { t: "KIM", n: "Kimco Realty", s: "Real Estate" },
  { t: "KKR", n: "KKR & Co.", s: "Financials" },
  { t: "KLAC", n: "KLA Corporation", s: "Technology" },
  { t: "KMB", n: "Kimberly-Clark", s: "Consumer Staples" },
  { t: "KMI", n: "Kinder Morgan", s: "Energy" },
  { t: "KO", n: "Coca-Cola Company (The)", s: "Consumer Staples" },
  { t: "KR", n: "Kroger", s: "Consumer Staples" },
  { t: "KVUE", n: "Kenvue", s: "Consumer Staples" },
  { t: "L", n: "Loews Corporation", s: "Financials" },
  { t: "LDOS", n: "Leidos", s: "Industrials" },
  { t: "LEN", n: "Lennar", s: "Consumer Disc." },
  { t: "LH", n: "Labcorp", s: "Healthcare" },
  { t: "LHX", n: "L3Harris", s: "Industrials" },
  { t: "LII", n: "Lennox International", s: "Industrials" },
  { t: "LIN", n: "Linde plc", s: "Materials" },
  { t: "LITE", n: "Lumentum", s: "Technology" },
  { t: "LLY", n: "Lilly (Eli)", s: "Healthcare" },
  { t: "LMT", n: "Lockheed Martin", s: "Industrials" },
  { t: "LNT", n: "Alliant Energy", s: "Utilities" },
  { t: "LOW", n: "Lowe's", s: "Consumer Disc." },
  { t: "LRCX", n: "Lam Research", s: "Technology" },
  { t: "LULU", n: "Lululemon Athletica", s: "Consumer Disc." },
  { t: "LUV", n: "Southwest Airlines", s: "Industrials" },
  { t: "LVS", n: "Las Vegas Sands", s: "Consumer Disc." },
  { t: "LYB", n: "LyondellBasell", s: "Materials" },
  { t: "LYV", n: "Live Nation Entertainment", s: "Communication" },
  { t: "MA", n: "Mastercard", s: "Financials" },
  { t: "MAA", n: "Mid-America Apartment Communities", s: "Real Estate" },
  { t: "MAR", n: "Marriott International", s: "Consumer Disc." },
  { t: "MAS", n: "Masco", s: "Industrials" },
  { t: "MCD", n: "McDonald's", s: "Consumer Disc." },
  { t: "MCHP", n: "Microchip Technology", s: "Technology" },
  { t: "MCK", n: "McKesson Corporation", s: "Healthcare" },
  { t: "MCO", n: "Moody's Corporation", s: "Financials" },
  { t: "MDLZ", n: "Mondelez International", s: "Consumer Staples" },
  { t: "MDT", n: "Medtronic", s: "Healthcare" },
  { t: "MET", n: "MetLife", s: "Financials" },
  { t: "META", n: "Meta Platforms", s: "Communication" },
  { t: "MGM", n: "MGM Resorts", s: "Consumer Disc." },
  { t: "MKC", n: "McCormick & Company", s: "Consumer Staples" },
  { t: "MLM", n: "Martin Marietta Materials", s: "Materials" },
  { t: "MMM", n: "3M", s: "Industrials" },
  { t: "MNST", n: "Monster Beverage", s: "Consumer Staples" },
  { t: "MO", n: "Altria", s: "Consumer Staples" },
  { t: "MOS", n: "Mosaic Company (The)", s: "Materials" },
  { t: "MPC", n: "Marathon Petroleum", s: "Energy" },
  { t: "MPWR", n: "Monolithic Power Systems", s: "Technology" },
  { t: "MRK", n: "Merck & Co.", s: "Healthcare" },
  { t: "MRNA", n: "Moderna", s: "Healthcare" },
  { t: "MRSH", n: "Marsh McLennan", s: "Financials" },
  { t: "MRVL", n: "Marvell Technology", s: "Technology" },
  { t: "MS", n: "Morgan Stanley", s: "Financials" },
  { t: "MSCI", n: "MSCI Inc.", s: "Financials" },
  { t: "MSFT", n: "Microsoft", s: "Technology" },
  { t: "MSI", n: "Motorola Solutions", s: "Technology" },
  { t: "MTB", n: "M&T Bank", s: "Financials" },
  { t: "MTD", n: "Mettler Toledo", s: "Healthcare" },
  { t: "MU", n: "Micron Technology", s: "Technology" },
  { t: "NCLH", n: "Norwegian Cruise Line Holdings", s: "Consumer Disc." },
  { t: "NDAQ", n: "Nasdaq, Inc.", s: "Financials" },
  { t: "NDSN", n: "Nordson Corporation", s: "Industrials" },
  { t: "NEE", n: "NextEra Energy", s: "Utilities" },
  { t: "NEM", n: "Newmont", s: "Materials" },
  { t: "NFLX", n: "Netflix", s: "Communication" },
  { t: "NI", n: "NiSource", s: "Utilities" },
  { t: "NKE", n: "Nike, Inc.", s: "Consumer Disc." },
  { t: "NOC", n: "Northrop Grumman", s: "Industrials" },
  { t: "NOW", n: "ServiceNow", s: "Technology" },
  { t: "NRG", n: "NRG Energy", s: "Utilities" },
  { t: "NSC", n: "Norfolk Southern", s: "Industrials" },
  { t: "NTAP", n: "NetApp", s: "Technology" },
  { t: "NTRS", n: "Northern Trust", s: "Financials" },
  { t: "NUE", n: "Nucor", s: "Materials" },
  { t: "NVDA", n: "Nvidia", s: "Technology" },
  { t: "NVR", n: "NVR, Inc.", s: "Consumer Disc." },
  { t: "NWS", n: "News Corp (Class B)", s: "Communication" },
  { t: "NWSA", n: "News Corp (Class A)", s: "Communication" },
  { t: "NXPI", n: "NXP Semiconductors", s: "Technology" },
  { t: "O", n: "Realty Income", s: "Real Estate" },
  { t: "ODFL", n: "Old Dominion", s: "Industrials" },
  { t: "OKE", n: "Oneok", s: "Energy" },
  { t: "OMC", n: "Omnicom Group", s: "Communication" },
  { t: "ON", n: "ON Semiconductor", s: "Technology" },
  { t: "ORCL", n: "Oracle Corporation", s: "Technology" },
  { t: "ORLY", n: "O’Reilly Automotive", s: "Consumer Disc." },
  { t: "OTIS", n: "Otis Worldwide", s: "Industrials" },
  { t: "OXY", n: "Occidental Petroleum", s: "Energy" },
  { t: "PANW", n: "Palo Alto Networks", s: "Technology" },
  { t: "PAYX", n: "Paychex", s: "Industrials" },
  { t: "PCAR", n: "Paccar", s: "Industrials" },
  { t: "PCG", n: "PG&E Corporation", s: "Utilities" },
  { t: "PEG", n: "Public Service Enterprise Group", s: "Utilities" },
  { t: "PEP", n: "PepsiCo", s: "Consumer Staples" },
  { t: "PFE", n: "Pfizer", s: "Healthcare" },
  { t: "PFG", n: "Principal Financial Group", s: "Financials" },
  { t: "PG", n: "Procter & Gamble", s: "Consumer Staples" },
  { t: "PGR", n: "Progressive Corporation", s: "Financials" },
  { t: "PH", n: "Parker Hannifin", s: "Industrials" },
  { t: "PHM", n: "PulteGroup", s: "Consumer Disc." },
  { t: "PKG", n: "Packaging Corporation of America", s: "Materials" },
  { t: "PLD", n: "Prologis", s: "Real Estate" },
  { t: "PLTR", n: "Palantir Technologies", s: "Technology" },
  { t: "PM", n: "Philip Morris International", s: "Consumer Staples" },
  { t: "PNC", n: "PNC Financial Services", s: "Financials" },
  { t: "PNR", n: "Pentair", s: "Industrials" },
  { t: "PNW", n: "Pinnacle West Capital", s: "Utilities" },
  { t: "PODD", n: "Insulet Corporation", s: "Healthcare" },
  { t: "PPG", n: "PPG Industries", s: "Materials" },
  { t: "PPL", n: "PPL Corporation", s: "Utilities" },
  { t: "PRU", n: "Prudential Financial", s: "Financials" },
  { t: "PSA", n: "Public Storage", s: "Real Estate" },
  { t: "PSKY", n: "Paramount Skydance Corporation", s: "Communication" },
  { t: "PSX", n: "Phillips 66", s: "Energy" },
  { t: "PTC", n: "PTC Inc.", s: "Technology" },
  { t: "PWR", n: "Quanta Services", s: "Industrials" },
  { t: "PYPL", n: "PayPal", s: "Financials" },
  { t: "Q", n: "Qnity Electronics", s: "Technology" },
  { t: "QCOM", n: "Qualcomm", s: "Technology" },
  { t: "RCL", n: "Royal Caribbean Group", s: "Consumer Disc." },
  { t: "REG", n: "Regency Centers", s: "Real Estate" },
  { t: "REGN", n: "Regeneron Pharmaceuticals", s: "Healthcare" },
  { t: "RF", n: "Regions Financial Corporation", s: "Financials" },
  { t: "RJF", n: "Raymond James Financial", s: "Financials" },
  { t: "RL", n: "Ralph Lauren Corporation", s: "Consumer Disc." },
  { t: "RMD", n: "ResMed", s: "Healthcare" },
  { t: "ROK", n: "Rockwell Automation", s: "Industrials" },
  { t: "ROL", n: "Rollins, Inc.", s: "Industrials" },
  { t: "ROP", n: "Roper Technologies", s: "Technology" },
  { t: "ROST", n: "Ross Stores", s: "Consumer Disc." },
  { t: "RSG", n: "Republic Services", s: "Industrials" },
  { t: "RTX", n: "RTX Corporation", s: "Industrials" },
  { t: "RVTY", n: "Revvity", s: "Healthcare" },
  { t: "SBAC", n: "SBA Communications", s: "Real Estate" },
  { t: "SBUX", n: "Starbucks", s: "Consumer Disc." },
  { t: "SCHW", n: "Charles Schwab Corporation", s: "Financials" },
  { t: "SHW", n: "Sherwin-Williams", s: "Materials" },
  { t: "SJM", n: "J.M. Smucker Company (The)", s: "Consumer Staples" },
  { t: "SLB", n: "Schlumberger", s: "Energy" },
  { t: "SMCI", n: "Supermicro", s: "Technology" },
  { t: "SNA", n: "Snap-on", s: "Industrials" },
  { t: "SNDK", n: "Sandisk", s: "Technology" },
  { t: "SNPS", n: "Synopsys", s: "Technology" },
  { t: "SO", n: "Southern Company", s: "Utilities" },
  { t: "SOLV", n: "Solventum", s: "Healthcare" },
  { t: "SPG", n: "Simon Property Group", s: "Real Estate" },
  { t: "SPGI", n: "S&P Global", s: "Financials" },
  { t: "SRE", n: "Sempra", s: "Utilities" },
  { t: "STE", n: "Steris", s: "Healthcare" },
  { t: "STLD", n: "Steel Dynamics", s: "Materials" },
  { t: "STT", n: "State Street Corporation", s: "Financials" },
  { t: "STX", n: "Seagate Technology", s: "Technology" },
  { t: "STZ", n: "Constellation Brands", s: "Consumer Staples" },
  { t: "SW", n: "Smurfit Westrock", s: "Materials" },
  { t: "SWK", n: "Stanley Black & Decker", s: "Industrials" },
  { t: "SWKS", n: "Skyworks Solutions", s: "Technology" },
  { t: "SYF", n: "Synchrony Financial", s: "Financials" },
  { t: "SYK", n: "Stryker Corporation", s: "Healthcare" },
  { t: "SYY", n: "Sysco", s: "Consumer Staples" },
  { t: "T", n: "AT&T", s: "Communication" },
  { t: "TAP", n: "Molson Coors Beverage Company", s: "Consumer Staples" },
  { t: "TDG", n: "TransDigm Group", s: "Industrials" },
  { t: "TDY", n: "Teledyne Technologies", s: "Technology" },
  { t: "TECH", n: "Bio-Techne", s: "Healthcare" },
  { t: "TEL", n: "TE Connectivity", s: "Technology" },
  { t: "TER", n: "Teradyne", s: "Technology" },
  { t: "TFC", n: "Truist Financial", s: "Financials" },
  { t: "TGT", n: "Target Corporation", s: "Consumer Staples" },
  { t: "TJX", n: "TJX Companies", s: "Consumer Disc." },
  { t: "TKO", n: "TKO Group Holdings", s: "Communication" },
  { t: "TMO", n: "Thermo Fisher Scientific", s: "Healthcare" },
  { t: "TMUS", n: "T-Mobile US", s: "Communication" },
  { t: "TPL", n: "Texas Pacific Land Corporation", s: "Energy" },
  { t: "TPR", n: "Tapestry, Inc.", s: "Consumer Disc." },
  { t: "TRGP", n: "Targa Resources", s: "Energy" },
  { t: "TRMB", n: "Trimble Inc.", s: "Technology" },
  { t: "TROW", n: "T. Rowe Price", s: "Financials" },
  { t: "TRV", n: "Travelers Companies (The)", s: "Financials" },
  { t: "TSCO", n: "Tractor Supply", s: "Consumer Disc." },
  { t: "TSLA", n: "Tesla, Inc.", s: "Consumer Disc." },
  { t: "TSN", n: "Tyson Foods", s: "Consumer Staples" },
  { t: "TT", n: "Trane Technologies", s: "Industrials" },
  { t: "TTD", n: "Trade Desk (The)", s: "Communication" },
  { t: "TTWO", n: "Take-Two Interactive", s: "Communication" },
  { t: "TXN", n: "Texas Instruments", s: "Technology" },
  { t: "TXT", n: "Textron", s: "Industrials" },
  { t: "TYL", n: "Tyler Technologies", s: "Technology" },
  { t: "UAL", n: "United Airlines Holdings", s: "Industrials" },
  { t: "UBER", n: "Uber", s: "Industrials" },
  { t: "UDR", n: "UDR, Inc.", s: "Real Estate" },
  { t: "UHS", n: "Universal Health Services", s: "Healthcare" },
  { t: "ULTA", n: "Ulta Beauty", s: "Consumer Disc." },
  { t: "UNH", n: "UnitedHealth Group", s: "Healthcare" },
  { t: "UNP", n: "Union Pacific Corporation", s: "Industrials" },
  { t: "UPS", n: "United Parcel Service", s: "Industrials" },
  { t: "URI", n: "United Rentals", s: "Industrials" },
  { t: "USB", n: "U.S. Bancorp", s: "Financials" },
  { t: "V", n: "Visa Inc.", s: "Financials" },
  { t: "VEEV", n: "Veeva Systems", s: "Healthcare" },
  { t: "VICI", n: "Vici Properties", s: "Real Estate" },
  { t: "VLO", n: "Valero Energy", s: "Energy" },
  { t: "VLTO", n: "Veralto", s: "Industrials" },
  { t: "VMC", n: "Vulcan Materials Company", s: "Materials" },
  { t: "VRSK", n: "Verisk Analytics", s: "Industrials" },
  { t: "VRSN", n: "Verisign", s: "Technology" },
  { t: "VRT", n: "Vertiv", s: "Industrials" },
  { t: "VRTX", n: "Vertex Pharmaceuticals", s: "Healthcare" },
  { t: "VST", n: "Vistra Corp.", s: "Utilities" },
  { t: "VTR", n: "Ventas", s: "Real Estate" },
  { t: "VTRS", n: "Viatris", s: "Healthcare" },
  { t: "VZ", n: "Verizon", s: "Communication" },
  { t: "WAB", n: "Wabtec", s: "Industrials" },
  { t: "WAT", n: "Waters Corporation", s: "Healthcare" },
  { t: "WBD", n: "Warner Bros. Discovery", s: "Communication" },
  { t: "WDAY", n: "Workday, Inc.", s: "Technology" },
  { t: "WDC", n: "Western Digital", s: "Technology" },
  { t: "WEC", n: "WEC Energy Group", s: "Utilities" },
  { t: "WELL", n: "Welltower", s: "Real Estate" },
  { t: "WFC", n: "Wells Fargo", s: "Financials" },
  { t: "WM", n: "Waste Management", s: "Industrials" },
  { t: "WMB", n: "Williams Companies", s: "Energy" },
  { t: "WMT", n: "Walmart", s: "Consumer Staples" },
  { t: "WRB", n: "W. R. Berkley Corporation", s: "Financials" },
  { t: "WSM", n: "Williams-Sonoma, Inc.", s: "Consumer Disc." },
  { t: "WST", n: "West Pharmaceutical Services", s: "Healthcare" },
  { t: "WTW", n: "Willis Towers Watson", s: "Financials" },
  { t: "WY", n: "Weyerhaeuser", s: "Real Estate" },
  { t: "WYNN", n: "Wynn Resorts", s: "Consumer Disc." },
  { t: "XEL", n: "Xcel Energy", s: "Utilities" },
  { t: "XOM", n: "ExxonMobil", s: "Energy" },
  { t: "XYL", n: "Xylem Inc.", s: "Industrials" },
  { t: "XYZ", n: "Block, Inc.", s: "Financials" },
  { t: "YUM", n: "Yum! Brands", s: "Consumer Disc." },
  { t: "ZBH", n: "Zimmer Biomet", s: "Healthcare" },
  { t: "ZBRA", n: "Zebra Technologies", s: "Technology" },
  { t: "ZTS", n: "Zoetis", s: "Healthcare" },
];
