// Top 100 US-listed stocks by market cap (snapshot: July 2026).
// To update the list, just edit this array — the wheel rebuilds itself automatically.
const STOCKS = [
  { t: "NVDA", n: "NVIDIA", s: "Technology" },
  { t: "MSFT", n: "Microsoft", s: "Technology" },
  { t: "AAPL", n: "Apple", s: "Technology" },
  { t: "GOOGL", n: "Alphabet", s: "Communication" },
  { t: "AMZN", n: "Amazon", s: "Consumer Disc." },
  { t: "META", n: "Meta Platforms", s: "Communication" },
  { t: "AVGO", n: "Broadcom", s: "Technology" },
  { t: "TSLA", n: "Tesla", s: "Consumer Disc." },
  { t: "BRK.B", n: "Berkshire Hathaway", s: "Financials" },
  { t: "LLY", n: "Eli Lilly", s: "Healthcare" },
  { t: "WMT", n: "Walmart", s: "Consumer Staples" },
  { t: "JPM", n: "JPMorgan Chase", s: "Financials" },
  { t: "V", n: "Visa", s: "Financials" },
  { t: "ORCL", n: "Oracle", s: "Technology" },
  { t: "MA", n: "Mastercard", s: "Financials" },
  { t: "XOM", n: "Exxon Mobil", s: "Energy" },
  { t: "UNH", n: "UnitedHealth", s: "Healthcare" },
  { t: "COST", n: "Costco", s: "Consumer Staples" },
  { t: "NFLX", n: "Netflix", s: "Communication" },
  { t: "PG", n: "Procter & Gamble", s: "Consumer Staples" },
  { t: "HD", n: "Home Depot", s: "Consumer Disc." },
  { t: "JNJ", n: "Johnson & Johnson", s: "Healthcare" },
  { t: "ABBV", n: "AbbVie", s: "Healthcare" },
  { t: "BAC", n: "Bank of America", s: "Financials" },
  { t: "CRM", n: "Salesforce", s: "Technology" },
  { t: "KO", n: "Coca-Cola", s: "Consumer Staples" },
  { t: "PLTR", n: "Palantir", s: "Technology" },
  { t: "PM", n: "Philip Morris", s: "Consumer Staples" },
  { t: "TMUS", n: "T-Mobile US", s: "Communication" },
  { t: "WFC", n: "Wells Fargo", s: "Financials" },
  { t: "CSCO", n: "Cisco", s: "Technology" },
  { t: "IBM", n: "IBM", s: "Technology" },
  { t: "GE", n: "GE Aerospace", s: "Industrials" },
  { t: "CVX", n: "Chevron", s: "Energy" },
  { t: "ABT", n: "Abbott Labs", s: "Healthcare" },
  { t: "MCD", n: "McDonald's", s: "Consumer Disc." },
  { t: "LIN", n: "Linde", s: "Materials" },
  { t: "AMD", n: "AMD", s: "Technology" },
  { t: "MRK", n: "Merck", s: "Healthcare" },
  { t: "DIS", n: "Disney", s: "Communication" },
  { t: "PEP", n: "PepsiCo", s: "Consumer Staples" },
  { t: "NOW", n: "ServiceNow", s: "Technology" },
  { t: "AXP", n: "American Express", s: "Financials" },
  { t: "GS", n: "Goldman Sachs", s: "Financials" },
  { t: "T", n: "AT&T", s: "Communication" },
  { t: "INTU", n: "Intuit", s: "Technology" },
  { t: "MS", n: "Morgan Stanley", s: "Financials" },
  { t: "UBER", n: "Uber", s: "Technology" },
  { t: "VZ", n: "Verizon", s: "Communication" },
  { t: "RTX", n: "RTX Corp", s: "Industrials" },
  { t: "CAT", n: "Caterpillar", s: "Industrials" },
  { t: "TXN", n: "Texas Instruments", s: "Technology" },
  { t: "BKNG", n: "Booking Holdings", s: "Consumer Disc." },
  { t: "ISRG", n: "Intuitive Surgical", s: "Healthcare" },
  { t: "QCOM", n: "Qualcomm", s: "Technology" },
  { t: "BLK", n: "BlackRock", s: "Financials" },
  { t: "TMO", n: "Thermo Fisher", s: "Healthcare" },
  { t: "SPGI", n: "S&P Global", s: "Financials" },
  { t: "ADBE", n: "Adobe", s: "Technology" },
  { t: "AMGN", n: "Amgen", s: "Healthcare" },
  { t: "HON", n: "Honeywell", s: "Industrials" },
  { t: "BSX", n: "Boston Scientific", s: "Healthcare" },
  { t: "SCHW", n: "Charles Schwab", s: "Financials" },
  { t: "UNP", n: "Union Pacific", s: "Industrials" },
  { t: "AMAT", n: "Applied Materials", s: "Technology" },
  { t: "NEE", n: "NextEra Energy", s: "Utilities" },
  { t: "C", n: "Citigroup", s: "Financials" },
  { t: "PGR", n: "Progressive", s: "Financials" },
  { t: "SYK", n: "Stryker", s: "Healthcare" },
  { t: "ETN", n: "Eaton", s: "Industrials" },
  { t: "PFE", n: "Pfizer", s: "Healthcare" },
  { t: "DHR", n: "Danaher", s: "Healthcare" },
  { t: "GILD", n: "Gilead Sciences", s: "Healthcare" },
  { t: "CMCSA", n: "Comcast", s: "Communication" },
  { t: "LOW", n: "Lowe's", s: "Consumer Disc." },
  { t: "ANET", n: "Arista Networks", s: "Technology" },
  { t: "TJX", n: "TJX Companies", s: "Consumer Disc." },
  { t: "MU", n: "Micron", s: "Technology" },
  { t: "DE", n: "Deere & Co", s: "Industrials" },
  { t: "BA", n: "Boeing", s: "Industrials" },
  { t: "COP", n: "ConocoPhillips", s: "Energy" },
  { t: "PANW", n: "Palo Alto Networks", s: "Technology" },
  { t: "KKR", n: "KKR & Co", s: "Financials" },
  { t: "ADP", n: "ADP", s: "Industrials" },
  { t: "VRTX", n: "Vertex Pharma", s: "Healthcare" },
  { t: "LRCX", n: "Lam Research", s: "Technology" },
  { t: "MDT", n: "Medtronic", s: "Healthcare" },
  { t: "SBUX", n: "Starbucks", s: "Consumer Disc." },
  { t: "KLAC", n: "KLA Corp", s: "Technology" },
  { t: "NKE", n: "Nike", s: "Consumer Disc." },
  { t: "CB", n: "Chubb", s: "Financials" },
  { t: "MMC", n: "Marsh & McLennan", s: "Financials" },
  { t: "UPS", n: "UPS", s: "Industrials" },
  { t: "INTC", n: "Intel", s: "Technology" },
  { t: "SO", n: "Southern Company", s: "Utilities" },
  { t: "CRWD", n: "CrowdStrike", s: "Technology" },
  { t: "PLD", n: "Prologis", s: "Real Estate" },
  { t: "AMT", n: "American Tower", s: "Real Estate" },
  { t: "CEG", n: "Constellation Energy", s: "Utilities" },
  { t: "MO", n: "Altria", s: "Consumer Staples" },
];
