// Top 100 US-listed stocks by market cap (snapshot: July 2026).
// To update the list, just edit this array — the wheel rebuilds itself automatically.
const TOP100 = [
  { t: "NVDA", n: "NVIDIA", s: "Technology" },
  { t: "MSFT", n: "Microsoft", s: "Technology" },
  { t: "AAPL", n: "Apple", s: "Technology" },
  { t: "GOOGL", n: "Alphabet", s: "Communication" },
  { t: "AMZN", n: "Amazon", s: "Consumer Disc." },
  { t: "META", n: "Meta Platforms", s: "Communication" },
  { t: "AVGO", n: "Broadcom", s: "Technology" },
  { t: "TSLA", n: "Tesla", s: "Consumer Disc." },
  { t: "BRK.B", n: "Berkshire Hathaway", s: "Financials" },
  { t: "LLY", n: "Eli Lilly", s: "Healthcare" },
  { t: "WMT", n: "Walmart", s: "Consumer Staples" },
  { t: "JPM", n: "JPMorgan Chase", s: "Financials" },
  { t: "V", n: "Visa", s: "Financials" },
  { t: "ORCL", n: "Oracle", s: "Technology" },
  { t: "MA", n: "Mastercard", s: "Financials" },
  { t: "XOM", n: "Exxon Mobil", s: "Energy" },
  { t: "UNH", n: "UnitedHealth", s: "Healthcare" },
  { t: "COST", n: "Costco", s: "Consumer Staples" },
  { t: "NFLX", n: "Netflix", s: "Communication" },
  { t: "PG", n: "Procter & Gamble", s: "Consumer Staples" },
  { t: "HD", n: "Home Depot", s: "Consumer Disc." },
  { t: "JNJ", n: "Johnson & Johnson", s: "Healthcare" },
  { t: "ABBV", n: "AbbVie", s: "Healthcare" },
  { t: "BAC", n: "Bank of America", s: "Financials" },
  { t: "CRM", n: "Salesforce", s: "Technology" },
  { t: "KO", n: "Coca-Cola", s: "Consumer Staples" },
  { t: "PLTR", n: "Palantir", s: "Technology" },
  { t: "PM", n: "Philip Morris", s: "Consumer Staples" },
  { t: "TMUS", n: "T-Mobile US", s: "Communication" },
  { t: "WFC", n: "Wells Fargo", s: "Financials" },
  { t: "CSCO", n: "Cisco", s: "Technology" },
  { t: "IBM", n: "IBM", s: "Technology" },
  { t: "GE", n: "GE Aerospace", s: "Industrials" },
  { t: "CVX", n: "Chevron", s: "Energy" },
  { t: "ABT", n: "Abbott Labs", s: "Healthcare" },
  { t: "MCD", n: "McDonald's", s: "Consumer Disc." },
  { t: "LIN", n: "Linde", s: "Materials" },
  { t: "AMD", n: "AMD", s: "Technology" },
  { t: "MRK", n: "Merck", s: "Healthcare" },
  { t: "DIS", n: "Disney", s: "Communication" },
  { t: "PEP", n: "PepsiCo", s: "Consumer Staples" },
  { t: "NOW", n: "ServiceNow", s: "Technology" },
  { t: "AXP", n: "American Express", s: "Financials" },
  { t: "GS", n: "Goldman Sachs", s: "Financials" },
  { t: "T", n: "AT&T", s: "Communication" },
  { t: "INTU", n: "Intuit", s: "Technology" },
  { t: "MS", n: "Morgan Stanley", s: "Financials" },
  { t: "UBER", n: "Uber", s: "Technology" },
  { t: "VZ", n: "Verizon", s: "Communication" },
  { t: "RTX", n: "RTX Corp", s: "Industrials" },
  { t: "CAT", n: "Caterpillar", s: "Industrials" },
  { t: "TXN", n: "Texas Instruments", s: "Technology" },
  { t: "BKNG", n: "Booking Holdings", s: "Consumer Disc." },
  { t: "ISRG", n: "Intuitive Surgical", s: "Healthcare" },
  { t: "QCOM", n: "Qualcomm", s: "Technology" },
  { t: "BLK", n: "BlackRock", s: "Financials" },
  { t: "TMO", n: "Thermo Fisher", s: "Healthcare" },
  { t: "SPGI", n: "S&P Global", s: "Financials" },
  { t: "ADBE", n: "Adobe", s: "Technology" },
  { t: "AMGN", n: "Amgen", s: "Healthcare" },
  { t: "HON", n: "Honeywell", s: "Industrials" },
  { t: "BSX", n: "Boston Scientific", s: "Healthcare" },
  { t: "SCHW", n: "Charles Schwab", s: "Financials" },
  { t: "UNP", n: "Union Pacific", s: "Industrials" },
  { t: "AMAT", n: "Applied Materials", s: "Technology" },
  { t: "NEE", n: "NextEra Energy", s: "Utilities" },
  { t: "C", n: "Citigroup", s: "Financials" },
  { t: "PGR", n: "Progressive", s: "Financials" },
  { t: "SYK", n: "Stryker", s: "Healthcare" },
  { t: "ETN", n: "Eaton", s: "Industrials" },
  { t: "PFE", n: "Pfizer", s: "Healthcare" },
  { t: "DHR", n: "Danaher", s: "Healthcare" },
  { t: "GILD", n: "Gilead Sciences", s: "Healthcare" },
  { t: "CMCSA", n: "Comcast", s: "Communication" },
  { t: "LOW", n: "Lowe's", s: "Consumer Disc." },
  { t: "ANET", n: "Arista Networks", s: "Technology" },
  { t: "TJX", n: "TJX Companies", s: "Consumer Disc." },
  { t: "MU", n: "Micron", s: "Technology" },
  { t: "DE", n: "Deere & Co", s: "Industrials" },
  { t: "BA", n: "Boeing", s: "Industrials" },
  { t: "COP", n: "ConocoPhillips", s: "Energy" },
  { t: "PANW", n: "Palo Alto Networks", s: "Technology" },
  { t: "KKR", n: "KKR & Co", s: "Financials" },
  { t: "ADP", n: "ADP", s: "Industrials" },
  { t: "VRTX", n: "Vertex Pharma", s: "Healthcare" },
  { t: "LRCX", n: "Lam Research", s: "Technology" },
  { t: "MDT", n: "Medtronic", s: "Healthcare" },
  { t: "SBUX", n: "Starbucks", s: "Consumer Disc." },
  { t: "KLAC", n: "KLA Corp", s: "Technology" },
  { t: "NKE", n: "Nike", s: "Consumer Disc." },
  { t: "CB", n: "Chubb", s: "Financials" },
  { t: "MMC", n: "Marsh & McLennan", s: "Financials" },
  { t: "UPS", n: "UPS", s: "Industrials" },
  { t: "INTC", n: "Intel", s: "Technology" },
  { t: "SO", n: "Southern Company", s: "Utilities" },
  { t: "CRWD", n: "CrowdStrike", s: "Technology" },
  { t: "PLD", n: "Prologis", s: "Real Estate" },
  { t: "AMT", n: "American Tower", s: "Real Estate" },
  { t: "CEG", n: "Constellation Energy", s: "Utilities" },
  { t: "MO", n: "Altria", s: "Consumer Staples" },
];

// High-volume names: consistently among the most actively traded US-listed
// stocks by daily share volume (curated snapshot, July 2026).
const HIGH_VOLUME = [
  { t: "NVDA", n: "NVIDIA", s: "Technology" },
  { t: "TSLA", n: "Tesla", s: "Consumer Disc." },
  { t: "PLTR", n: "Palantir", s: "Technology" },
  { t: "AAPL", n: "Apple", s: "Technology" },
  { t: "AMD", n: "AMD", s: "Technology" },
  { t: "INTC", n: "Intel", s: "Technology" },
  { t: "AMZN", n: "Amazon", s: "Consumer Disc." },
  { t: "MSFT", n: "Microsoft", s: "Technology" },
  { t: "GOOGL", n: "Alphabet", s: "Communication" },
  { t: "META", n: "Meta Platforms", s: "Communication" },
  { t: "AVGO", n: "Broadcom", s: "Technology" },
  { t: "MU", n: "Micron", s: "Technology" },
  { t: "SMCI", n: "Super Micro", s: "Technology" },
  { t: "F", n: "Ford", s: "Consumer Disc." },
  { t: "SOFI", n: "SoFi Technologies", s: "Financials" },
  { t: "HOOD", n: "Robinhood", s: "Financials" },
  { t: "COIN", n: "Coinbase", s: "Financials" },
  { t: "MSTR", n: "Strategy", s: "Technology" },
  { t: "MARA", n: "MARA Holdings", s: "Technology" },
  { t: "RIOT", n: "Riot Platforms", s: "Technology" },
  { t: "CLSK", n: "CleanSpark", s: "Technology" },
  { t: "LCID", n: "Lucid Group", s: "Consumer Disc." },
  { t: "RIVN", n: "Rivian", s: "Consumer Disc." },
  { t: "NIO", n: "NIO", s: "Consumer Disc." },
  { t: "XPEV", n: "XPeng", s: "Consumer Disc." },
  { t: "GM", n: "General Motors", s: "Consumer Disc." },
  { t: "UBER", n: "Uber", s: "Technology" },
  { t: "SNAP", n: "Snap", s: "Communication" },
  { t: "WBD", n: "Warner Bros. Discovery", s: "Communication" },
  { t: "T", n: "AT&T", s: "Communication" },
  { t: "VZ", n: "Verizon", s: "Communication" },
  { t: "CMCSA", n: "Comcast", s: "Communication" },
  { t: "BAC", n: "Bank of America", s: "Financials" },
  { t: "WFC", n: "Wells Fargo", s: "Financials" },
  { t: "C", n: "Citigroup", s: "Financials" },
  { t: "JPM", n: "JPMorgan Chase", s: "Financials" },
  { t: "SCHW", n: "Charles Schwab", s: "Financials" },
  { t: "PFE", n: "Pfizer", s: "Healthcare" },
  { t: "BMY", n: "Bristol-Myers Squibb", s: "Healthcare" },
  { t: "MRK", n: "Merck", s: "Healthcare" },
  { t: "CVS", n: "CVS Health", s: "Healthcare" },
  { t: "WMT", n: "Walmart", s: "Consumer Staples" },
  { t: "KO", n: "Coca-Cola", s: "Consumer Staples" },
  { t: "KVUE", n: "Kenvue", s: "Consumer Staples" },
  { t: "XOM", n: "Exxon Mobil", s: "Energy" },
  { t: "OXY", n: "Occidental Petroleum", s: "Energy" },
  { t: "DVN", n: "Devon Energy", s: "Energy" },
  { t: "AAL", n: "American Airlines", s: "Industrials" },
  { t: "UAL", n: "United Airlines", s: "Industrials" },
  { t: "DAL", n: "Delta Air Lines", s: "Industrials" },
  { t: "CCL", n: "Carnival", s: "Consumer Disc." },
  { t: "NCLH", n: "Norwegian Cruise Line", s: "Consumer Disc." },
  { t: "DKNG", n: "DraftKings", s: "Consumer Disc." },
  { t: "CSCO", n: "Cisco", s: "Technology" },
  { t: "DELL", n: "Dell Technologies", s: "Technology" },
  { t: "ORCL", n: "Oracle", s: "Technology" },
  { t: "QCOM", n: "Qualcomm", s: "Technology" },
  { t: "AMAT", n: "Applied Materials", s: "Technology" },
  { t: "ON", n: "ON Semiconductor", s: "Technology" },
  { t: "GRAB", n: "Grab Holdings", s: "Technology" },
  { t: "PYPL", n: "PayPal", s: "Financials" },
  { t: "XYZ", n: "Block", s: "Financials" },
  { t: "NU", n: "Nu Holdings", s: "Financials" },
  { t: "ITUB", n: "Itaú Unibanco", s: "Financials" },
  { t: "BBD", n: "Banco Bradesco", s: "Financials" },
  { t: "VALE", n: "Vale", s: "Materials" },
  { t: "PBR", n: "Petrobras", s: "Energy" },
  { t: "ABEV", n: "Ambev", s: "Consumer Staples" },
  { t: "BABA", n: "Alibaba", s: "Consumer Disc." },
  { t: "PLUG", n: "Plug Power", s: "Industrials" },
  { t: "CHPT", n: "ChargePoint", s: "Industrials" },
  { t: "GME", n: "GameStop", s: "Consumer Disc." },
  { t: "AMC", n: "AMC Entertainment", s: "Communication" },
  { t: "OPEN", n: "Opendoor", s: "Real Estate" },
  { t: "SOUN", n: "SoundHound AI", s: "Technology" },
  { t: "BBAI", n: "BigBear.ai", s: "Technology" },
  { t: "IONQ", n: "IonQ", s: "Technology" },
  { t: "RGTI", n: "Rigetti Computing", s: "Technology" },
  { t: "ACHR", n: "Archer Aviation", s: "Industrials" },
  { t: "JOBY", n: "Joby Aviation", s: "Industrials" },
];

// Degen mode: memes, crypto plays, quantum lottos, leveraged ETFs. YOLO.
const DEGEN = [
  { t: "GME", n: "GameStop", s: "Meme" },
  { t: "AMC", n: "AMC Entertainment", s: "Meme" },
  { t: "KOSS", n: "Koss Corp", s: "Meme" },
  { t: "BB", n: "BlackBerry", s: "Meme" },
  { t: "CLOV", n: "Clover Health", s: "Meme" },
  { t: "DJT", n: "Trump Media", s: "Meme" },
  { t: "OPEN", n: "Opendoor", s: "Meme" },
  { t: "CVNA", n: "Carvana", s: "Meme" },
  { t: "BYND", n: "Beyond Meat", s: "Meme" },
  { t: "PTON", n: "Peloton", s: "Meme" },
  { t: "W", n: "Wayfair", s: "Meme" },
  { t: "CHWY", n: "Chewy", s: "Meme" },
  { t: "RDDT", n: "Reddit", s: "Meme" },
  { t: "TLRY", n: "Tilray", s: "Meme" },
  { t: "CGC", n: "Canopy Growth", s: "Meme" },
  { t: "MSTR", n: "Strategy", s: "Crypto" },
  { t: "COIN", n: "Coinbase", s: "Crypto" },
  { t: "HOOD", n: "Robinhood", s: "Crypto" },
  { t: "CRCL", n: "Circle", s: "Crypto" },
  { t: "MARA", n: "MARA Holdings", s: "Crypto" },
  { t: "RIOT", n: "Riot Platforms", s: "Crypto" },
  { t: "CLSK", n: "CleanSpark", s: "Crypto" },
  { t: "HUT", n: "Hut 8", s: "Crypto" },
  { t: "BITF", n: "Bitfarms", s: "Crypto" },
  { t: "WULF", n: "TeraWulf", s: "Crypto" },
  { t: "IREN", n: "IREN", s: "Crypto" },
  { t: "CIFR", n: "Cipher Mining", s: "Crypto" },
  { t: "HIVE", n: "HIVE Digital", s: "Crypto" },
  { t: "BTBT", n: "Bit Digital", s: "Crypto" },
  { t: "GLXY", n: "Galaxy Digital", s: "Crypto" },
  { t: "IONQ", n: "IonQ", s: "Quantum" },
  { t: "RGTI", n: "Rigetti Computing", s: "Quantum" },
  { t: "QUBT", n: "Quantum Computing Inc", s: "Quantum" },
  { t: "QBTS", n: "D-Wave Quantum", s: "Quantum" },
  { t: "ARQQ", n: "Arqit Quantum", s: "Quantum" },
  { t: "ASTS", n: "AST SpaceMobile", s: "Space" },
  { t: "RKLB", n: "Rocket Lab", s: "Space" },
  { t: "LUNR", n: "Intuitive Machines", s: "Space" },
  { t: "RDW", n: "Redwire", s: "Space" },
  { t: "BKSY", n: "BlackSky", s: "Space" },
  { t: "ACHR", n: "Archer Aviation", s: "Space" },
  { t: "JOBY", n: "Joby Aviation", s: "Space" },
  { t: "LCID", n: "Lucid Group", s: "EV / Green" },
  { t: "RIVN", n: "Rivian", s: "EV / Green" },
  { t: "NIO", n: "NIO", s: "EV / Green" },
  { t: "PLUG", n: "Plug Power", s: "EV / Green" },
  { t: "FCEL", n: "FuelCell Energy", s: "EV / Green" },
  { t: "CHPT", n: "ChargePoint", s: "EV / Green" },
  { t: "QS", n: "QuantumScape", s: "EV / Green" },
  { t: "SOUN", n: "SoundHound AI", s: "AI Hype" },
  { t: "BBAI", n: "BigBear.ai", s: "AI Hype" },
  { t: "AI", n: "C3.ai", s: "AI Hype" },
  { t: "UPST", n: "Upstart", s: "AI Hype" },
  { t: "SMCI", n: "Super Micro", s: "AI Hype" },
  { t: "TEM", n: "Tempus AI", s: "AI Hype" },
  { t: "SERV", n: "Serve Robotics", s: "AI Hype" },
  { t: "AFRM", n: "Affirm", s: "AI Hype" },
  { t: "SOFI", n: "SoFi Technologies", s: "AI Hype" },
  { t: "TQQQ", n: "3x Long Nasdaq-100", s: "Leveraged ETF" },
  { t: "SQQQ", n: "3x Short Nasdaq-100", s: "Leveraged ETF" },
  { t: "SOXL", n: "3x Long Semiconductors", s: "Leveraged ETF" },
  { t: "SOXS", n: "3x Short Semiconductors", s: "Leveraged ETF" },
  { t: "SPXL", n: "3x Long S&P 500", s: "Leveraged ETF" },
  { t: "SPXS", n: "3x Short S&P 500", s: "Leveraged ETF" },
  { t: "TNA", n: "3x Long Small Caps", s: "Leveraged ETF" },
  { t: "LABU", n: "3x Long Biotech", s: "Leveraged ETF" },
  { t: "YINN", n: "3x Long China", s: "Leveraged ETF" },
  { t: "TSLL", n: "2x Long TSLA", s: "Leveraged ETF" },
  { t: "NVDL", n: "2x Long NVDA", s: "Leveraged ETF" },
  { t: "UVXY", n: "1.5x Long VIX Futures", s: "Leveraged ETF" },
];

// Wheel modes. `list` is what goes on the wheel.
const MODES = [
  { key: "top100", label: "Top 100", desc: "100 biggest US stocks by market cap", list: TOP100 },
  { key: "sp500", label: "S&P 500", desc: "All 503 S&P 500 constituents", list: SP500 },
  { key: "volume", label: "High Volume", desc: "Most actively traded names — easy in, easy out", list: HIGH_VOLUME },
  { key: "degen", label: "Degen 🎰", desc: "Memes, crypto, quantum & leveraged ETFs. YOLO.", list: DEGEN },
];

